using ERMS.Domain.Enums;
namespace ERMS.Application.DTOs;

public sealed record LoginRequest(string Email, string Password);
public sealed record RefreshRequest(string RefreshToken);
public sealed record ChangePasswordRequest(string CurrentPassword, string NewPassword);
public sealed record UserSummary(int Id, string FullName, string Email, UserRole Role, string Department, int? ManagerId, bool IsActive, bool MustChangePassword);
public sealed record AuthResponse(string AccessToken, string RefreshToken, DateTime ExpiresAt, UserSummary User);
public sealed record CreateRequestDto(int RequestTypeId, string? Title, string? Description, DateTime? StartDate, DateTime? EndDate, decimal? Amount, RequestPriority Priority, bool SaveAsDraft);
public sealed record UpdateRequestDto(int RequestTypeId, string? Title, string? Description, DateTime? StartDate, DateTime? EndDate, decimal? Amount, RequestPriority Priority);
public sealed record RequestListItem(int Id, string Title, string Type, RequestStatus Status, RequestPriority Priority, string Requester, DateTime CreatedAt);
public sealed record PagedResult<T>(int Page, int PageSize, int TotalCount, IReadOnlyList<T> Items);
public sealed record ApprovalDto(int Id, string Decision, string Approver, string? Comment, DateTime DecidedAt);
public sealed record CommentDto(int Id, string Author, string Content, DateTime CreatedAt);
public sealed record AttachmentDto(int Id, string FileName, string ContentType, long FileSize, DateTime CreatedAt);
public sealed record HistoryDto(int Id, int RequestId, string? OldStatus, string NewStatus, string Action, string ChangedBy, DateTime ChangedAt);
public sealed record RequestDetailDto(int Id, int RequestTypeId, string Type, int RequesterId, string Requester, string Title, string Description, RequestStatus Status, RequestPriority Priority, DateTime? StartDate, DateTime? EndDate, decimal? Amount, DateTime CreatedAt, DateTime UpdatedAt, IReadOnlyList<ApprovalDto> Approvals, IReadOnlyList<CommentDto> Comments, IReadOnlyList<AttachmentDto> Attachments, IReadOnlyList<HistoryDto> History);
public sealed record DecisionRequest(string? Comment);
public sealed record CommentRequest(string Content);
public sealed record RequestTypeDto(int Id, string Name, bool RequiresApproval, bool IsActive);
public sealed record DepartmentDto(int Id, string Name, bool IsActive);
public sealed record CreateUserRequest(string FirstName, string LastName, string Email, string Password, UserRole Role, int DepartmentId, int? ManagerId);
public sealed record UpdateUserRequest(string FirstName, string LastName, string Email, UserRole Role, int DepartmentId, int? ManagerId, bool IsActive, string? NewPassword);
public sealed record UpsertDepartmentRequest(string Name, bool IsActive = true);
public sealed record UpsertRequestTypeRequest(string Name, bool RequiresApproval, bool IsActive = true);
public sealed record FilePayload(string FileName, string ContentType, Stream Content, long Length);
public sealed record StoredFile(string StoredFileName, Stream Content);
public sealed record NotificationDto(int Id, int? RequestId, string Type, string Title, string Message, bool IsRead, DateTime CreatedAt);
public sealed record NotificationListDto(int UnreadCount, IReadOnlyList<NotificationDto> Items);
